### ISSUE TITLE
Sprockets 3+

### ISSUE THREAD

**Issue by ghost** [franzheidl/sass-inline-svg#9]
On running
```
bundle exec rake assets:precompile RAILS_ENV=production RAILS_RELATIVE_URL_ROOT=/path
```
I get the error
```
rake aborted!
NoMethodError: undefined method `find_asset' for nil:NilClass
/usr/local/share/svdv/vendor/bundle/ruby/2.1.0/gems/sass_inline_svg-0.0.6/lib/sass_inline_svg.rb:18:in `inline_svg'
/usr/local/share/svdv/vendor/bundle/ruby/2.1.0/gems/sass-3.4.23/lib/sass/script/tree/funcall.rb:143:in `_perform'
  :
/usr/local/share/svdv/vendor/bundle/ruby/2.1.0/gems/sprockets-3.7.1/lib/rake/sprocketstask.rb:147:in `with_logger'
/usr/local/share/svdv/vendor/bundle/ruby/2.1.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
/usr/local/share/svdv/vendor/bundle/ruby/2.1.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
```
A quick search on the error message leads me to [this](http://stackoverflow.com/questions/35251759/undefined-method-find-asset-for-nilnilclass/37820647), and applying the same solution as suggested there, i.e., setting `config.assets.compile = true` in `config/environments/production.rb` fixes the issue for me; but I thought it worthwhile to mention it here.

My setup: Rails 4.2.7.1, Sprockets 3.7.1, Sass-inline-svg 0.0.6

And thanks for the Gem, very useful!

**Comment by franzheidl** [comment]
Should be fixed by #10.
